/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.embeddediq.searchmonkey;

/**
 *
 * @author cottr
 */
public class SearchSummaryPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchSummary
     */
    public SearchSummaryPanel() {
        initComponents();
        ShowProgress(false);
        SetProgress("Pending");
        SetStatus("Ready");
        SetSearched("");
        SetSelected("");
    }
    
    public void SetSelected(String msg)
    {
        jSearchSelect.setText(msg);
    }
    public void SetSearched(String msg)
    {
        jSearchSummary.setText(msg);
    }
    public void ShowProgress(boolean val)
    {
        jStatus.setVisible(!val);
        jProgressBar1.setVisible(val);
    }
    public void SetProgress(String msg)
    {
        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setString(msg);
        jProgressBar1.setStringPainted(true);
    }
    
    public void SetProgress(int val)
    {
        jProgressBar1.setIndeterminate(false);
        jProgressBar1.setString(String.format("%d%%", val));
        jProgressBar1.setValue(val);
    }
    public void SetStatus(String msg)
    {
        jStatus.setText(msg);
        //ShowProgress(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStatus = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jSearchSummary = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jSearchSelect = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jStatus.setText("Ready");
        add(jStatus);

        jProgressBar1.setToolTipText("");
        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setPreferredSize(new java.awt.Dimension(100, 14));
        jProgressBar1.setStringPainted(true);
        add(jProgressBar1);
        add(filler1);

        jSearchSummary.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSearchSummary.setText("Found: 16 items (300 MB)");
        add(jSearchSummary);
        add(filler2);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setMaximumSize(new java.awt.Dimension(10, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 10));
        add(jSeparator1);

        jSearchSelect.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSearchSelect.setText("Selected: One item (2 MB)");
        add(jSearchSelect);
        add(filler3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel jSearchSelect;
    private javax.swing.JLabel jSearchSummary;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jStatus;
    // End of variables declaration//GEN-END:variables
}
