#baseurl = "https://manjaro.org/"
#baseurl = "https://rumangerst.github.io/homepage/public/"
baseurl = "https://cottrela.github.io/searchmonkey/public/"
languageCode = "en-us"
title = "Searchmonkey - power searching without the pain"
theme = "hugo-creative-theme"

[params]

	name = "Manjaro Linux"
	description = "Linux Distribution"

	# The path must be relative to the static folder
	favicon = "favicon.png"

 	[params.language]
		current = "English"

		[[params.language.available]]
			name = "English"
			url = "https://manjaro.org/"

	# Navigation
	[params.navigation.main]
		brand = "Manjaro"
		about     = "About"
		services  = "Features"
		download = "Downloads"
		contact   = "Contact"
		donate   = "Donate"
		news = "News"
		support = "Support"
		getinvolved = "Get involved"

	[params.navigation.download]
		home = "Overview"
		community_editions = "Manjaro Community Editions"
		preview_editions = "Developer previews"

	[params.navigation.features]
		home = "About Manjaro"

	[params.navigation.news]
		home = "Most recent news"
		archives = "More archives"

	[params.navigation.support]
		home = "Overview"
		wiki = "Wiki"
		forum = "Forum"
		email = "E-Mail"

	[params.navigation.getinvolved]
		home = "You can help!"
		forum = "Forums"
		donate = "Donate"
		bugs = "Bugtracker"
		team = "Our team"
		sponsors = "Our sponsors"

	# Hero section*
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		image = "manjaro-logo.png	"
		slogan     = "manjaro linux"
		subslogan = "Fast & stable."
		#subtitle   = "The easy to install Linux distribution with a friendly feel that comes with the latest and greatest apps at your fingertips."
		subtitle = "The Linux distribution that is easy to install, stable and always up-to-date."

		callToAction = "Learn more about Manjaro"
		callToActionUrl = "#about"
		learnMore = "or download directly"
		learnMoreUrl = "#downloads"

	[params.posthome]
		callToAction = "Download now"
		callToActionUrl = ";baseurl;download"

	[params.team]
		name = "Name"
		alias = "Alias"
		role = "Role"
		involvements = "Involements"
		email = "E-Mail"
		languages = "Languages"
		location = "Location"
		yob = "Year of birth"


	# About section
	[params.about]
		headline    = "Grows with you"
		description = "Built from the powerful Arch Linux foundation; speed, efficiency and cutting edge software is in its core that is rock solid and stable. Manjaro is designed to welcome a newcomer and grow with the user as he evolves into a power user."
		buttonText  = "Get started!"

	# Contact section
	[params.donate]
		headline = "Help us"
		description = "Besides participating in discussions to improve Manjaro, helping other users or help developing new functions, you can always donate money to help keeping our infrastructure funded. Just a few bucks can help to keep our website and forums ad-free, reliable and secure."
		conditions = "A donation counts as a private donation and is kept anonymous by us. That means that we won't share or publish any details about you and your donation. Donators get no rights or privileges - everybody can participate, whether they donated or not. Manjaro is still relatively young and a growing distribution - we are no registered organization. That means that we cannot give you a reciept that deduct taxes. For the same reason, the donation cannot go to a 'Manjaro Linux' organization, but goes to the head of the Manjaro team."

		[params.donate.account]
			account_holder = "Hanns Philip Müller"
			account_number = "1050676905"
			bank_identification = "12030000"
			bank = "DKB"
			bic = "BYLADEM1001"
			iban = "DE90120300001050676905"
			purpose = "Donation to Manjaro Linux"
			note = "If you want a confirmation that we got your donation, just add your E-Mail adress to the purpose."

	[params.download_edition]
		download_x64_title = "64 bit version"
		download_x86_title = "32 bit version"
		download_x64_button = "Download 64 bit version"
		download_x86_button = "Download 32 bit version"
		download_x64_description = "Download the 64 bit version if you use a modern computer and the the maximum performance and full benefits of your modern hardware."
		download_x86_description = "Download the 32 bit version if you use an older computer or if you are unsure if your computer supports the 64 bit version."
		download_gpg = "Download GPG signature"
		download_torrent = "Download Torrent"