/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_folderChooserDialog (void);
GtkWidget* create_menu1 (void);
GtkWidget* create_highlightColourDialog (void);
GtkWidget* create_fontSelectionDialog (void);
GtkWidget* create_clearSearchHistoryDialog (void);
GtkWidget* create_testRegExDialog (void);
GtkWidget* create_expWizard (void);
GtkWidget* create_configDialog (void);
GtkWidget* create_saveFileDialog (void);
GtkWidget* create_importCriteria (void);
GtkWidget* create_exportCriteria (void);
GtkWidget* create_autoComplete (void);
GtkWidget* create_aboutSearchmonkey (void);
GtkWidget* create_creditsDialog (void);
GtkWidget* create_calendarDialog (void);
